### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Tcheetox** [entvex/NgrokSharp#14]
Hey thanks for your work so far!
I was wondering if it is possible to avoid to DownloadAndUnszipNgrok() every time if already present and/or provide a path to the .exe?
Cheers

**Comment by entvex** [comment]
Dear @Tcheetox. Thanks for reaching out! I am happy you find my open source software useful 👍.
I would like to work on a change in the lib, so you can provide a path to the Ngrok executable :)

**Comment by entvex** [comment]
I should be able to have it done this week @Tcheetox :)

**Comment by Tcheetox** [comment]
Awesome! Thanks.

**Comment by entvex** [comment]
Dear @Tcheetox.
The code to solve your problem is now in this branch https://github.com/entvex/NgrokSharp/tree/ProvideAWayToSeTThePathToNgrok. Now you can point to a folder where the ngrok executable is located. I'll write unit tests for the feature soon, and then make a new release 👍 

> Hey thanks for your work so far! I was wondering if it is possible to avoid to DownloadAndUnszipNgrok() every time if already present and/or provide a path to the .exe? Cheers

Another thing I was thinking about. When you have used DownloadAndUnszipNgrok() once on a system. You don't need to run it again on the same system. Everything is ready, and you should just be able to start using the library. I just wanted to make sure it made sense.

I hope it makes sense, if not feel free to ask :)

**Comment by Tcheetox** [comment]
Amazing, thanks!

Not sure to understand what you meant about DownloadAndUnzipNgrok(), is it:
- I need to run it once per system (responsibility of the caller to detect its already there)
- The method detects if its already available and in such case the method does nothing.

Anyway, its good to be able to point towards a file/directory because I wish to ship my project with the executable already included. 

Cheers.

**Comment by entvex** [comment]
> Amazing, thanks!
> 
> Not sure to understand what you meant about DownloadAndUnzipNgrok(), is it:
> 
>     * I need to run it once per system (responsibility of the caller to detect its already there)
> 
>     * The method detects if its already available and in such case the method does nothing.
> 

If you run DownloadAndUnzipNgrok it will basically just download ngrok and if it already exists overwrite it :)

> 
> Anyway, its good to be able to point towards a file/directory because I wish to ship my project with the executable already included.
> 
> Cheers.

Yeah, I agree. I'll start writing the unit tests now 👍. A new release should be available soon if everything goes well.
I will let you know when it is released.

**Comment by entvex** [comment]
Dear @Tcheetox 

Now there is a new [nuget packget](https://www.nuget.org/packages/NgrokSharp/) with the requested feature. Please see the [docs here](https://entvex.github.io/NgrokSharp/api/NgrokSharp.INgrokManager.html#NgrokSharp_INgrokManager_SetNgrokDirectory_System_String_)

Please let me know if works for you :)
